<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robocraft_gz_plugins</name>
  <version>2.0.0</version>
  <description>Gazebo Fortress system plugins for the RoboCraft cell (sensor-verified grasp / platform brake).</description>
  <maintainer email="basheeraltaweel@gmail.com">Basheer Al-Tawil</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ignition-gazebo6</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
