"""Generate controllers.yaml (mock/real) and controllers_gazebo.yaml.

Run from this directory after changing controller settings:  python3 generate_controllers.py
"""
ARMS = ["arm1", "arm2", "arm3"]
# Gazebo velocity-loop gains per joint: P [1/s]; feed-forward = trajectory velocity
GAINS = {1: 25.0, 2: 25.0, 3: 30.0, 4: 15.0}


def build(gazebo: bool) -> str:
    out = ["""# ros2_control configuration of the RoboCraft cell (%s).
# GENERATED by generate_controllers.py - edit that file, not this one.
# One controller manager, one JointTrajectoryController per arm (serial mode:
# arms are commanded independently; parallel mode: the cell interface sends
# time-synchronised goals with a common start stamp to all gripping arms),
# one GripperActionController per rack-and-pinion gripper.
controller_manager:
  ros__parameters:
    update_rate: 250  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
""" % ("Gazebo: velocity command interface" if gazebo else "mock / real: position command interface")]
    for a in ARMS:
        out.append(f"""    {a}_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    {a}_gripper_controller:
      type: position_controllers/GripperActionController
""")
    for a in ARMS:
        joints = [f"{a}_joint{i}" for i in range(1, 5)]
        tol = "\n".join(
            f"      {n}: {{trajectory: {0.08 if i < 3 else 0.02 if i == 3 else 0.2}, goal: {0.01 if i != 3 else 0.003}}}"
            for i, n in enumerate(joints, 1))
        gains = ""
        if gazebo:
            gains = "    gains:\n" + "\n".join(
                f"      {n}: {{p: {GAINS[i]}, i: 0.0, d: 0.0, i_clamp: 0.0, ff_velocity_scale: 1.0}}"
                for i, n in enumerate(joints, 1)) + "\n"
        out.append(f"""
{a}_controller:
  ros__parameters:
    joints: [{', '.join(joints)}]
    command_interfaces: [{'velocity' if gazebo else 'position'}]
    state_interfaces: [position, velocity]
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: false
{gains}    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 1.0
{tol}

{a}_gripper_controller:
  ros__parameters:
    joint: {a}_finger_left_joint
    goal_tolerance: 0.002
    max_effort: 20.0
    allow_stalling: true
    stall_velocity_threshold: 0.001
    stall_timeout: 0.5
""")
    return "".join(out)


if __name__ == "__main__":
    open("controllers.yaml", "w").write(build(False))
    open("controllers_gazebo.yaml", "w").write(build(True))
